repos:
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: "0.0.2"
    hooks:
      - id: stylelint
        files: assets/sass/.*\.scss$
        additional_dependencies:
          - "stylelint@16.25.0"
          - "stylelint-config-standard-scss@16.0.0"
  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.3.5"
    hooks:
      - id: biome-check
        files: assets/js/.*\.js$
        additional_dependencies:
          - "@biomejs/biome@1.9.4"
